application: hackerdojo-signin
version: 1
runtime: python
api_version: 1

inbound_services:
- mail
  
builtins:
- appstats: on
  
handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /static
  static_dir: static
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
- url: .*
  script: main.py


